# Generated by Django 4.1.12 on 2023-10-11 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0003_alter_category_options_alter_level_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='level',
            name='comment',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='isbn',
            field=models.CharField(max_length=16),
        ),
    ]
