# Generated by Django 4.1.12 on 2023-10-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0005_alter_title_category_id_alter_title_level_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='handle',
        ),
        migrations.AlterField(
            model_name='title',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='storage/'),
        ),
        migrations.AlterField(
            model_name='title',
            name='isbn',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
