# Generated by Django 4.1.12 on 2023-10-19 14:21

import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0006_remove_title_handle_alter_title_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TitleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/Users/melmav/Documents/kast/kast/micro-ecommerce/local-cdn/protected'), upload_to='attachments/')),
                ('is_free', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='storage.title')),
            ],
        ),
    ]
