# Generated by Django 4.1.12 on 2023-10-25 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0008_alter_title_language_alter_title_origin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
