# Generated by Django 4.1.12 on 2023-10-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0009_alter_title_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
