# Generated by Django 4.1.12 on 2023-11-02 14:35

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0010_alter_title_updated'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='title',
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
