# Generated by Django 4.1.12 on 2023-11-02 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0011_alter_title_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='handle',
            field=models.SlugField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='title',
            name='category_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='storage.category'),
        ),
        migrations.AlterField(
            model_name='title',
            name='cover',
            field=models.ImageField(blank=True, default='storage/book.avif', null=True, upload_to='storage/'),
        ),
    ]
