# Generated by Django 4.1.12 on 2024-01-17 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0014_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
