# Generated by Django 4.1.12 on 2024-02-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0015_title_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='amount',
        ),
        migrations.AddField(
            model_name='title',
            name='books_per_box',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='placebook',
            name='copies_num',
            field=models.IntegerField(null=True),
        ),
    ]
