# Generated by Django 4.1.12 on 2024-02-13 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0017_placebook_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='ignore_amount',
            field=models.BooleanField(default=False),
        ),
    ]
