# Generated by Django 4.1.12 on 2024-02-13 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0018_title_ignore_amount'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='placebook',
            unique_together={('title', 'place')},
        ),
    ]
